INSERT INTO category (id, description) VALUES (1, 'American');
INSERT INTO category (id, description) VALUES (2, 'Italian');
INSERT INTO category (id, description) VALUES (3, 'Mexican');
INSERT INTO category (id, description) VALUES (4, 'Fast Food');
INSERT INTO unit_of_measure (id, description) VALUES (1, 'teaspoon');
INSERT INTO unit_of_measure (id, description) VALUES (2, 'tablespoon');
INSERT INTO unit_of_measure (id, description) VALUES (3, 'cup');
INSERT INTO unit_of_measure (id, description) VALUES (4, 'pinch');
INSERT INTO unit_of_measure (id, description) VALUES (5, 'dash');
INSERT INTO unit_of_measure (id, description) VALUES (6, 'ounce');
INSERT INTO unit_of_measure (id, description) VALUES (7, '');
INSERT INTO unit_of_measure (id, description) VALUES (8, 'pint');
